cpufreq: sprd: move unused prototypes to blocked area
This patch blocks unused prototypes which causes following build
error on specific toolchains.

   In file included from include/asm-generic/percpu.h:6:0,
                    from /home/sw0312.kim/linux-3.10-sc7730/arch/arm/include/asm/percpu.h:50,
                    from include/linux/percpu.h:10,
                    from include/linux/kernel_stat.h:6,
                    from drivers/cpufreq/cpufreq_sprdemand.c:18:
   drivers/cpufreq/cpufreq_sprdemand.c: At top level:
   drivers/cpufreq/cpufreq_sprdemand.c:101:48: error: storage size of 'uwi' isn't known
    static DEFINE_PER_CPU(struct unplug_work_info, uwi);
                                                ^

Change-Id: Ida47ea5e16a2f3f8883afe37adf9fcb9975c9ef1
Reported-by: Sung-jae Park <nicesj@nicesj.com>
Signed-off-by: Seung-Woo Kim <sw0312.kim@samsung.com>